kind: Deployment
apiVersion: apps/v1
metadata:
   name: user-service
spec:
   replicas: 1
   selector:
      matchLabels:
         app: user-service
   template:
      metadata:
         name: user-service
         labels:
            app: user-service
      spec:
         containers:
         -  name: user-service
            image: qualitto007/user-service:latest
            imagePullPolicy: Always
            ports:
            -  containerPort: 9092
---
kind: Service
apiVersion: v1
metadata:
   name: user-service-k8srv
   labels:
      app: user-service-k8srv
spec:
   ports:
    - port: 9092
   selector:
      app: user-service