---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: qualitto007/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9093
---
kind: Service
apiVersion: v1
metadata:
  name: user-service-service
  labels:
    app: user-service-service
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 9093
    targetPort: 9093
  selector:
    app: user-service-service
